### ISSUE TITLE
Subutai Console does not show update

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/peer-os#2601] opened 2018-08-03 11:48 UTC
* Bazaar shows that update for rh is available, but you can't update it from SC, because there's no update
![image 2](https://user-images.githubusercontent.com/22586805/43641422-68fd1ed2-9745-11e8-807f-2db572c5e1ec.png)
![image 1](https://user-images.githubusercontent.com/22586805/43641423-691e22ee-9745-11e8-835d-027ef1caddf9.png)
[karaflogs2018-08-03 17_27_12.txt](https://github.com/subutai-io/peer-os/files/2257229/karaflogs2018-08-03.17_27_12.txt)

**Comment by Dilshat** [comment] 2018-08-03 11:49
subutai update management -c fails with error `Another update process is already running`

**Comment by Dilshat** [comment] 2018-08-03 14:13
Console might also show that update is not available when another earlier update is in progress. 
So this might be not a bug but a normal condition

**Comment by Dilshat** [comment] 2018-09-05 06:38
The bug with missing updates was fixed in release https://github.com/subutai-io/peer-os/releases/tag/7.0.7

**Closed by Dilshat** 2018-09-05 06:38 UTC
